name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # ЭТАП 1: Сборка и отправка образа (выполняется на серверах GitHub)
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USER }}/auto-site:v1

  # ЭТАП 2: Развертывание (выполняется на ТВОЕМ личном сервере Ubuntu)
  deploy:
    needs: build # Ждем, пока Этап 1 завершится успешно
    runs-on: self-hosted # Вот тут магия! Робот запускает этот этап на твоем сервере
    
    steps:
    - name: Deploy new version
      run: |
        # 1. Переходим в папку проекта
        cd ~/my_wordpress
        
        # 2. Скачиваем свежий образ с Docker Hub
        docker pull ${{ secrets.DOCKER_USER }}/auto-site:v1
        
        # 3. Перезапускаем контейнеры (заменят старые на новые)
        docker compose up -d
